### ISSUE TITLE
About camera intrinsics

### ISSUE THREAD

**Issue by csyhping** [Karbo123/RGBD-Diffusion#4]
Hi @Karbo123 , thanks for your great work. 

May I ask why there is a preprocessing for the camera intrinsic? [L71](https://github.com/Karbo123/RGBD-Diffusion/blob/19a243ae46fa599e6415df306d55940fbc4b324a/dataset/ScanNet/main_scene.py#L71) and [L72](https://github.com/Karbo123/RGBD-Diffusion/blob/19a243ae46fa599e6415df306d55940fbc4b324a/dataset/ScanNet/main_scene.py#L72). 

What are `/480` and `(img_size / 2) * 0.3333` for?

Thanks!

**Comment by Karbo123** [comment]
Good question, but I'm not so sure because it was a long time ago. I guess this is because there is a small inconsistency between the loaded image and the desired image resolution. See [here](https://github.com/Karbo123/RGBD-Diffusion/blob/19a243ae46fa599e6415df306d55940fbc4b324a/dataset/ScanNet/main_scene.py#L168-L172), we crop the image and resize it to 128x128, so maybe the intrinsics should be changed as well.
